---
title: "R Notebook"
output:
  word_document: default
  html_notebook: default
---


| **Category**                                                                                                                       | **Assessment**                                                                                                                                                                                                                                                                                                                                                                                                                           |
| ---------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **1. Definition of PICO and estimand**                                                                                             |                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| Population                                                                                                                         | Population of interest                                                                                                                                                                                                                                                                                                                                                                                                                   |
| Intervention                                                                                                                       | Intervention applied in the experimental arm                                                                                                                                                                                                                                                                                                                                                                                             |
| Comparator                                                                                                                         | - Data source  <br>- Rationale for using RWD<br>- Multiple therapeutic strategies employed                                                                                                                                                                                                                                                                                                                                               |
| Endpoint and measure                                                                                                               | Endpoint used to assess the efficacy of the intervention                                                                                                                                                                                                                                                                                                                                                                                 |
| Intercurrent events                                                                                                                | Method for assessing intercurrent events (*pas collecté*)                                                                                                                                                                                                                                                                                                                                                                                |
| Estimand                                                                                                                           | Type of estimand                                                                                                                                                                                                                                                                                                                                                                                                                         |
|                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| **2. Selection of RWD external control arm**                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| Homogeneity of populations                                                                                                         | **Arm comparability**<br>- Consistent inclusion criteria across arms  <br>~~- Hernán method inclusion criteria (when control units = LOTs)  ~~<br>- Identical centers across both arms <br>- Mean number of centers per arm <br>~~- Matching countries across both arms (*pas collecté*)~~<br><br>**Temporal alignment**<br>- Enrollment inception in both arms ~~("*ancienneté*")~~<br>- Enrollment gap between arms ~~("*décalage*")~~ |
| Treatment onset and characteristics                                                                                                | - Consistent index date definition across arms<br>- Description of treatment strategy in the control arm (ici ou 3.a?)                                                                                                                                                                                                                                                                                                                   |
|                                                                                                                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| **3. Methods for indirect comparison**                                                                                             |                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| **a. Identifiability hypotheses**                                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| Consistency ~~(well defined and precise intervention that would yield identical outcome under identical experimental conditions)~~ | - Consistent outcome assessment (*pas collecté*)<br>- Description of treatment strategy in the control arm (ici ou 2?)<br>- Multiple treatment strategies in control arm                                                                                                                                                                                                                                                                 |
| Stable Unit Treatment Value Assumption or SUTVA ~~(the outcome of an individual only depends on their intervention)~~              | *Checked a priori in drug evaluation*                                                                                                                                                                                                                                                                                                                                                                                                    |
| Conditional independence ~~(the conditional probability of belonging to the either arm only depends on measured covariates)~~      | - Rationale for covariate selection ~~(based on literature review and expert knowledge)~~<br>- Between groups baseline comparison<br>- Planned assessment of covariate balance between arms after adjustment                                                                                                                                                                                                                             |
| Positivity ~~(for every value of each covariate there is a non null probability of receiving either intervention)~~                | Planned assessment of covariate or propensity score (if applicable) distribution overlap after adjustment                                                                                                                                                                                                                                                                                                                                |
| **b. Statistical considerations**                                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| Endpoint                                                                                                                           | Definition of the endpoint (strength, objectivity, and type)                                                                                                                                                                                                                                                                                                                                                                             |
| Multiplicity                                                                                                                       | Approach for handling multiplicity, if applicable                                                                                                                                                                                                                                                                                                                                                                                        |
| Missing data                                                                                                                       | Method for handling missing data                                                                                                                                                                                                                                                                                                                                                                                                         |
| Sample size                                                                                                                        | Justification of sample size for both arms and parameters used ~~(see notes from 20/03/25)~~                                                                                                                                                                                                                                                                                                                                             |
| Adjustment                                                                                                                         | Method used to adjust for baseline arm comparability                                                                                                                                                                                                                                                                                                                                                                                     |
| Results robustness                                                                                                                 | Sensitivity analyses and their comparability to the primary analysis                                                                                                                                                                                                                                                                                                                                                                     |